import type { AttendanceRecord, AttendanceStats } from "./attendanceTypes";

export const SAMPLE_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  // ── Ravi Kumar — completed shift, 3 interval check-ins ──
  {
    id: "att-001",
    guardId: "guard-rk01",
    guardName: "Ravi Kumar",
    guardEmployeeCode: "RK-001",
    guardInitials: "RK",
    guardAvatarColor: "#7c3aed",
    agencyId: "agency-001",
    siteId: "site-tcs",
    siteName: "TCS Gate 1",
    postName: "Main Entrance",
    punchInDate: "2026-10-07",
    punchInTime: "08:02 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=12",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.5204,
    punchInLng: 73.8567,
    punchInAccuracyMeters: 8,
    punchOutTime: "05:04 PM",
    punchOutSelfieUrl: "https://i.pravatar.cc/280?img=13",
    punchOutGeofenceStatus: "passed",
    durationMinutes: 542,
    intervalCheckins: [
      {
        id: "ci-001-1",
        sequenceNumber: 1,
        checkinTime: "10:02 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=14",
        geofenceStatus: "passed",
        lat: 18.5205,
        lng: 73.8566,
        accuracyMeters: 10,
      },
      {
        id: "ci-001-2",
        sequenceNumber: 2,
        checkinTime: "12:02 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=16",
        geofenceStatus: "passed",
        lat: 18.5203,
        lng: 73.8568,
        accuracyMeters: 9,
      },
      {
        id: "ci-001-3",
        sequenceNumber: 3,
        checkinTime: "02:02 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=17",
        geofenceStatus: "passed",
        lat: 18.5204,
        lng: 73.8567,
        accuracyMeters: 7,
      },
    ],
  },

  // ── Sachin Kadam — on shift, 2 interval check-ins so far ──
  {
    id: "att-002",
    guardId: "guard-sk03",
    guardName: "Sachin Kadam",
    guardEmployeeCode: "SK-003",
    guardInitials: "SK",
    guardAvatarColor: "#2563eb",
    agencyId: "agency-001",
    siteId: "site-infosys",
    siteName: "Infosys Campus",
    postName: "North Wing",
    punchInDate: "2026-10-07",
    punchInTime: "09:15 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=33",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.6298,
    punchInLng: 73.7997,
    punchInAccuracyMeters: 12,
    punchOutTime: null,
    punchOutSelfieUrl: null,
    punchOutGeofenceStatus: null,
    durationMinutes: null,
    intervalCheckins: [
      {
        id: "ci-002-1",
        sequenceNumber: 1,
        checkinTime: "11:15 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=35",
        geofenceStatus: "passed",
        lat: 18.6299,
        lng: 73.7996,
        accuracyMeters: 11,
      },
      {
        id: "ci-002-2",
        sequenceNumber: 2,
        checkinTime: "01:15 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=36",
        geofenceStatus: "passed",
        lat: 18.6298,
        lng: 73.7998,
        accuracyMeters: 13,
      },
    ],
  },

  // ── Priya Singh — completed shift, 2 interval check-ins ──
  {
    id: "att-003",
    guardId: "guard-ps07",
    guardName: "Priya Singh",
    guardEmployeeCode: "PS-007",
    guardInitials: "PS",
    guardAvatarColor: "#db2777",
    agencyId: "agency-001",
    siteId: "site-phoenix",
    siteName: "Phoenix Mall",
    postName: "Floor 2 Security",
    punchInDate: "2026-10-07",
    punchInTime: "07:45 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=44",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.5679,
    punchInLng: 73.9143,
    punchInAccuracyMeters: 6,
    punchOutTime: "04:30 PM",
    punchOutSelfieUrl: "https://i.pravatar.cc/280?img=45",
    punchOutGeofenceStatus: "passed",
    durationMinutes: 525,
    intervalCheckins: [
      {
        id: "ci-003-1",
        sequenceNumber: 1,
        checkinTime: "10:00 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=46",
        geofenceStatus: "passed",
        lat: 18.5680,
        lng: 73.9142,
        accuracyMeters: 8,
      },
      {
        id: "ci-003-2",
        sequenceNumber: 2,
        checkinTime: "12:15 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=47",
        geofenceStatus: "passed",
        lat: 18.5679,
        lng: 73.9144,
        accuracyMeters: 7,
      },
    ],
  },

  // ── Amar Nath — on shift, demo_passed, no interval check-ins ──
  {
    id: "att-004",
    guardId: "guard-an12",
    guardName: "Amar Nath",
    guardEmployeeCode: "AN-012",
    guardInitials: "AN",
    guardAvatarColor: "#d97706",
    agencyId: "agency-001",
    siteId: "site-tcs",
    siteName: "TCS Gate 1",
    postName: "Back Gate",
    punchInDate: "2026-10-07",
    punchInTime: "08:30 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=15",
    punchInGeofenceStatus: "demo_passed",
    punchInLat: 18.5201,
    punchInLng: 73.8570,
    punchInAccuracyMeters: 42,
    punchOutTime: null,
    punchOutSelfieUrl: null,
    punchOutGeofenceStatus: null,
    durationMinutes: null,
    intervalCheckins: [],
  },

  // ── Deepak Verma — completed shift, 2 interval check-ins ──
  {
    id: "att-005",
    guardId: "guard-dv19",
    guardName: "Deepak Verma",
    guardEmployeeCode: "DV-019",
    guardInitials: "DV",
    guardAvatarColor: "#059669",
    agencyId: "agency-001",
    siteId: "site-infosys",
    siteName: "Infosys Campus",
    postName: "Server Room",
    punchInDate: "2026-10-07",
    punchInTime: "10:00 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=52",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.6302,
    punchInLng: 73.8001,
    punchInAccuracyMeters: 9,
    punchOutTime: "06:00 PM",
    punchOutSelfieUrl: "https://i.pravatar.cc/280?img=53",
    punchOutGeofenceStatus: "passed",
    durationMinutes: 480,
    intervalCheckins: [
      {
        id: "ci-005-1",
        sequenceNumber: 1,
        checkinTime: "12:00 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=54",
        geofenceStatus: "passed",
        lat: 18.6303,
        lng: 73.8000,
        accuracyMeters: 10,
      },
      {
        id: "ci-005-2",
        sequenceNumber: 2,
        checkinTime: "02:00 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=55",
        geofenceStatus: "passed",
        lat: 18.6301,
        lng: 73.8002,
        accuracyMeters: 8,
      },
    ],
  },

  // ── Suresh Patil — completed shift, no interval check-ins ──
  {
    id: "att-006",
    guardId: "guard-sp31",
    guardName: "Suresh Patil",
    guardEmployeeCode: "SP-031",
    guardInitials: "SP",
    guardAvatarColor: "#dc2626",
    agencyId: "agency-001",
    siteId: "site-tcs",
    siteName: "TCS Gate 1",
    postName: "Parking Zone",
    punchInDate: "2026-10-07",
    punchInTime: "08:00 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=20",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.5207,
    punchInLng: 73.8564,
    punchInAccuracyMeters: 5,
    punchOutTime: "04:00 PM",
    punchOutSelfieUrl: "https://i.pravatar.cc/280?img=21",
    punchOutGeofenceStatus: "passed",
    durationMinutes: 480,
    intervalCheckins: [],
  },

  // ── Kiran Sharma — on shift, 1 interval check-in ──
  {
    id: "att-007",
    guardId: "guard-ks08",
    guardName: "Kiran Sharma",
    guardEmployeeCode: "KS-008",
    guardInitials: "KS",
    guardAvatarColor: "#0891b2",
    agencyId: "agency-001",
    siteId: "site-infosys",
    siteName: "Infosys Campus",
    postName: "Gate B",
    punchInDate: "2026-10-07",
    punchInTime: "09:00 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=31",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.6295,
    punchInLng: 73.7999,
    punchInAccuracyMeters: 11,
    punchOutTime: null,
    punchOutSelfieUrl: null,
    punchOutGeofenceStatus: null,
    durationMinutes: null,
    intervalCheckins: [
      {
        id: "ci-007-1",
        sequenceNumber: 1,
        checkinTime: "11:00 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=32",
        geofenceStatus: "passed",
        lat: 18.6296,
        lng: 73.7998,
        accuracyMeters: 12,
      },
    ],
  },

  // ── Rajesh Tomar — completed shift, 3 interval check-ins ──
  {
    id: "att-008",
    guardId: "guard-rt22",
    guardName: "Rajesh Tomar",
    guardEmployeeCode: "RT-022",
    guardInitials: "RT",
    guardAvatarColor: "#6d28d9",
    agencyId: "agency-001",
    siteId: "site-phoenix",
    siteName: "Phoenix Mall",
    postName: "Main Entrance",
    punchInDate: "2026-10-07",
    punchInTime: "07:55 AM",
    punchInSelfieUrl: "https://i.pravatar.cc/280?img=68",
    punchInGeofenceStatus: "passed",
    punchInLat: 18.5682,
    punchInLng: 73.9140,
    punchInAccuracyMeters: 7,
    punchOutTime: "05:55 PM",
    punchOutSelfieUrl: "https://i.pravatar.cc/280?img=69",
    punchOutGeofenceStatus: "passed",
    durationMinutes: 600,
    intervalCheckins: [
      {
        id: "ci-008-1",
        sequenceNumber: 1,
        checkinTime: "09:55 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=70",
        geofenceStatus: "passed",
        lat: 18.5683,
        lng: 73.9139,
        accuracyMeters: 8,
      },
      {
        id: "ci-008-2",
        sequenceNumber: 2,
        checkinTime: "11:55 AM",
        selfieUrl: "https://i.pravatar.cc/280?img=71",
        geofenceStatus: "passed",
        lat: 18.5681,
        lng: 73.9141,
        accuracyMeters: 9,
      },
      {
        id: "ci-008-3",
        sequenceNumber: 3,
        checkinTime: "01:55 PM",
        selfieUrl: "https://i.pravatar.cc/280?img=72",
        geofenceStatus: "passed",
        lat: 18.5682,
        lng: 73.9140,
        accuracyMeters: 6,
      },
    ],
  },
];

export const SAMPLE_ATTENDANCE_STATS: AttendanceStats = {
  presentToday: 8,
  absentToday: 4,
  onShift: 3,
};

export const SAMPLE_SITES = [
  { siteId: "site-tcs", siteName: "TCS Gate 1" },
  { siteId: "site-infosys", siteName: "Infosys Campus" },
  { siteId: "site-phoenix", siteName: "Phoenix Mall" },
];
