export const attendanceMarkedDefaults = {
  screenTitle: 'Patrol Session',
  shiftCommencedLabel: 'SHIFT COMMENCED',
  successTitle: 'Attendance Marked!',
  successSubtitle: 'Punch-in recorded successfully',
  guardName: 'Rajesh Kumar',
  guardId: 'RKS-8842',
  activeDutyLabel: 'Active On Duty',
  verifiedPhotoLabel: 'Verified',
  punchInLabel: 'Punch-in Time',
  punchInTime: '07:55 AM',
  punchInStatus: 'On Time',
  punchInDate: 'Monday, 24 October 2024',
  dutySiteLabel: 'Duty Site & Post',
  dutySiteName: 'ABC Green Valley Heights',
  dutyPostName: 'Checkpoint Post Gate 3 (Main Entry)',
  rosterLabel: 'Assigned Roster',
  rosterTitle: 'Day Duty (12 hrs)',
  rosterHours: '08:00 AM – 08:00 PM',
  geofenceTitle: 'Geofence Compliance',
  geofenceDetail: 'Site Match: 100% (Accuracy: 3m)',
  geofenceResult: 'PASSED',
  dispatchTitle: 'Dispatched to Roster Command',
  dispatchMessage:
    'Control Room and Supervisor Amit Singh have been notified with live location lock.',
  doneButtonLabel: 'Done • Go to Home',
  scheduleButtonLabel: "View Today's Duty Schedule",
} as const;
