export type LoginMode = 'phone' | 'id';

export const loginScreenDefaults = {
  brandName: 'Raksha',
  brandSubtitle: 'Security Ops',
  crestLogoUri:
    'https://lh3.googleusercontent.com/aida/AEtjO1VzGWwvo7ZU_6wNMClVzC21ZMIOGKS6a3Zu65o8X8VFqCwq8Z9awXUPToKs-FzFr1uJz7NQoyBYnJb7gR1_QQQ4vmVsR3pGfQoHY1I0CInHk5YvbKICwDIa9VY6TXErw4mzlLohJrYll_9XQ7HFO12JCGSmbDR3NHFuCpS8PJoHvtqrHm8aWeWeMHQ9WstFA6xoqwsr17oRvs1s5QSd02-pgVduk9pgFq8J_KvCpIicGIQh3sM1rhZJFNzO',
  langLabelEnglish: 'English • हिंदी',
  langLabelHindi: 'हिंदी (Hindi)',
  authorizedBadge: 'Authorized Personnel Only',
  welcomeTitle: 'Welcome to Raksha',
  welcomeSubtitle: 'सुरक्षा कर्मी प्रवेश पोर्टल • Sign in to start your duty',
  modePhoneLabel: 'Mobile Number',
  modeIdLabel: 'Guard ID / आईडी',
  phoneLabel: 'Mobile Number / मोबाइल नंबर',
  phoneLabelHindi: 'मोबाइल नंबर',
  phoneHint: 'Registered SIM',
  phonePlaceholder: 'Enter 10-digit mobile',
  phoneDefault: '9876543210',
  idLabel: 'Guard ID / गार्ड आईडी',
  idLabelHindi: 'गार्ड आईडी नंबर',
  idHint: 'Badge / PSARA ID',
  idPlaceholder: 'e.g. RKS-8842',
  idDefault: 'RKS-8842-DL',
  otpLabel: 'Enter 6-Digit Code / ओटीपी',
  otpAutoDetect: 'Auto-Detecting',
  resendPrefix: 'Resend in',
  resendReady: 'Ready',
  callOtpLabel: 'Get Call OTP (कॉल करें)',
  verifyLabel: 'Verify & Enter Duty',
  verifyLabelHindi: 'सत्यापित करें और ड्यूटी शुरू करें',
  forgotPinLabel: 'Forgot PIN / Password? (पिन भूल गए?)',
  controlRoomLabel: 'Control Room 1800-100-200',
  controlRoomTel: '1800100200',
  supervisorLabel: 'Field Supervisor',
  supervisorTel: '+919811223344',
  complianceLabel: 'ISO 27001 Certified • PSARA Security Compliant',
  forgotPinAlertTitle: 'PIN Reset',
  forgotPinAlertMessage:
    'Supervisor notification triggered: ID badge verification token dispatched to Shift In-charge (सुपरवाइज़र को अलर्ट भेजा गया है)',
  voiceOtpAlertTitle: 'Voice OTP',
  voiceOtpAlertMessage: 'Calling registered mobile ending in 3210 with voice OTP code.',
  successAlertTitle: 'Authentication Successful',
  successAlertMessage: 'Shift activated at Gate 3. Duty started.',
  otpInitial: ['5', '8', '2', '4', '9', ''] as string[],
  resendSeconds: 24,
} as const;
