import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const guardProfileDigitalIdCardStyles = StyleSheet.create({
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  topBar: {
    backgroundColor: appColors.primary,
    paddingHorizontal: appSpacing.md,
    paddingVertical: appSpacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.xs,
    flex: 1,
    minWidth: 0,
  },
  topBarLabel: {
    ...appTypography.labelLg,
    color: appColors.primaryFixed,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    flexShrink: 1,
  },
  activeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: appColors.primaryContainer,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.full,
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#34d399',
  },
  activeText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onPrimaryContainer,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  body: {
    padding: appSpacing.md,
    gap: appSpacing.md,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: appSpacing.xs,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  cardTitle: {
    ...appTypography.titleLg,
    color: appColors.onSurface,
  },
  idBadge: {
    backgroundColor: appColors.surfaceContainerHigh,
    paddingHorizontal: appSpacing.sm,
    paddingVertical: 4,
    borderRadius: appRadii.lg,
    alignItems: 'flex-end',
  },
  idLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.secondary,
    textTransform: 'uppercase',
  },
  idValue: {
    ...appTypography.labelXl,
    color: appColors.primary,
    letterSpacing: -0.3,
  },
  identityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.md,
  },
  photoWrap: {
    width: 96,
    height: 96,
    borderRadius: appRadii.xl,
    overflow: 'hidden',
    backgroundColor: appColors.surfaceContainerHigh,
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  gradeBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 70, 74, 0.85)',
    paddingVertical: 2,
    alignItems: 'center',
  },
  gradeText: {
    fontSize: 10,
    lineHeight: 12,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onPrimary,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  identityCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  name: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
  },
  role: {
    ...appTypography.bodyLg,
    color: appColors.secondary,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: appSpacing.xs,
    marginTop: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: appColors.surfaceContainer,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: appRadii.md,
  },
  chipText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onSurface,
  },
  qrBlock: {
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.xl,
    padding: appSpacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: appSpacing.md,
  },
  qrCopy: {
    flex: 1,
    minWidth: 0,
  },
  qrTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  qrTitle: {
    ...appTypography.labelLg,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  qrHint: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
    marginTop: 4,
  },
  validRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  validText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onSurfaceVariant,
  },
  qrTap: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: appRadii.xl,
    padding: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  qrTapPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  qrTapLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 4,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: appSpacing.sm,
    paddingTop: appSpacing.xs,
  },
  secondaryAction: {
    flex: 1,
    minHeight: 50,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surfaceContainer,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: appSpacing.xs,
    paddingHorizontal: appSpacing.sm,
  },
  primaryAction: {
    flex: 1,
    minHeight: 50,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.primaryContainer,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: appSpacing.xs,
    paddingHorizontal: appSpacing.sm,
  },
  actionLabel: {
    ...appTypography.labelLg,
    color: appColors.onSurface,
    flexShrink: 1,
  },
  primaryActionLabel: {
    ...appTypography.labelLg,
    color: appColors.onPrimary,
    flexShrink: 1,
  },
  actionPressed: {
    opacity: 0.92,
  },
  footerBar: {
    backgroundColor: appColors.surfaceContainerHigh,
    paddingHorizontal: appSpacing.md,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  footerHash: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.secondary,
  },
});
