import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const guardProfileSectionCardStyles = StyleSheet.create({
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: 16,
    padding: appSpacing.md,
    gap: appSpacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.xs,
    flex: 1,
    minWidth: 0,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: appRadii.lg,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrapError: {
    backgroundColor: appColors.surfaceContainer,
  },
  title: {
    ...appTypography.titleLg,
    color: appColors.onSurface,
    flexShrink: 1,
  },
  headerBadge: {
    backgroundColor: appColors.surfaceContainer,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.full,
  },
  headerBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  headerMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.primary,
  },
  headerMetaMuted: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_500Medium',
    color: appColors.secondary,
  },
  stack: {
    gap: appSpacing.sm,
  },
  stackTight: {
    gap: appSpacing.xs,
  },
  infoBlock: {
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.xl,
    padding: appSpacing.sm,
  },
  infoRow: {
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.xl,
    padding: appSpacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.sm,
  },
  infoRowStart: {
    alignItems: 'flex-start',
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: appColors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCopy: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.secondary,
    textTransform: 'uppercase',
  },
  fieldValue: {
    ...appTypography.labelXl,
    color: appColors.onSurface,
  },
  fieldValueLg: {
    ...appTypography.labelLg,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  fieldMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
  },
  fieldMeta14: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
  },
  mono: {
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onSurface,
  },
  rosterChip: {
    backgroundColor: 'rgba(30, 94, 99, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: appRadii.lg,
  },
  rosterChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.primaryContainer,
  },
  callButton: {
    width: 48,
    height: 48,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emergencyCall: {
    width: 48,
    height: 48,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.errorContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listItem: {
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.xl,
    padding: appSpacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  listLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: appSpacing.sm,
    flex: 1,
    minWidth: 0,
  },
  listLeftCenter: {
    alignItems: 'center',
  },
  statusIconSuccess: {
    width: 32,
    height: 32,
    borderRadius: appRadii.lg,
    backgroundColor: '#d1fae5',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  statusIconNeutral: {
    width: 32,
    height: 32,
    borderRadius: appRadii.lg,
    backgroundColor: appColors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  listCopy: {
    flex: 1,
    minWidth: 0,
  },
  listTitle: {
    ...appTypography.labelLg,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  listMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
  },
  listDetail: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.onSurfaceVariant,
  },
  statusSuccess: {
    backgroundColor: '#d1fae5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.sm,
  },
  statusSuccessText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_700Bold',
    color: '#065f46',
    textTransform: 'uppercase',
  },
  statusNeutral: {
    backgroundColor: appColors.surfaceContainerHigh,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.sm,
  },
  statusNeutralText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.9,
  },
});
