import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const guardProfileModalsStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: appSpacing.lg,
    maxHeight: '90%',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: appSpacing.sm,
  },
  sheetTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
    flexShrink: 1,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrPanel: {
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: 16,
    padding: appSpacing.lg,
    alignItems: 'center',
    marginVertical: appSpacing.sm,
  },
  qrFrame: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  auditName: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
    textAlign: 'center',
    marginTop: appSpacing.md,
  },
  auditId: {
    ...appTypography.labelXl,
    color: appColors.primary,
    textAlign: 'center',
  },
  auditAgency: {
    ...appTypography.bodyLg,
    color: appColors.secondary,
    textAlign: 'center',
    marginTop: 4,
  },
  verifiedPill: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#d1fae5',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: appRadii.full,
  },
  verifiedDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#059669',
  },
  verifiedText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_700Bold',
    color: '#064e3b',
  },
  brightnessRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  brightnessText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
  },
  doneButton: {
    minHeight: 56,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  doneLabel: {
    ...appTypography.labelXl,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onPrimary,
  },
  logoutBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: appSpacing.md,
  },
  logoutCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: 16,
    padding: appSpacing.lg,
    gap: appSpacing.md,
  },
  warningIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: appColors.errorContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutTitle: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
  },
  logoutMessage: {
    ...appTypography.bodyLg,
    color: appColors.secondary,
    marginTop: 4,
  },
  logoutActions: {
    flexDirection: 'row',
    gap: appSpacing.sm,
    paddingTop: 8,
  },
  cancelButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelLabel: {
    ...appTypography.labelLg,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  confirmButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmLabel: {
    ...appTypography.labelLg,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onError,
  },
  toast: {
    backgroundColor: appColors.inverseSurface,
    borderRadius: appRadii.xl,
    paddingHorizontal: appSpacing.md,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.sm,
  },
  toastText: {
    ...appTypography.labelLg,
    color: appColors.inverseOnSurface,
    flex: 1,
  },
  pressed: {
    opacity: 0.9,
  },
});
