import { StyleSheet } from 'react-native';

import { appColors, appLayout, appSpacing, appTypography } from '../theme';

export const layoutTopHeaderBarStyles = StyleSheet.create({
  wrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: 'rgba(248, 249, 255, 0.92)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  bar: {
    height: appLayout.headerHeight,
    paddingHorizontal: appSpacing.gutter,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.sm,
    flex: 1,
    minWidth: 0,
    paddingRight: appSpacing.sm,
  },
  logo: {
    width: 32,
    height: 32,
  },
  brand: {
    ...appTypography.headlineSm,
    color: appColors.primary,
    letterSpacing: -0.3,
    lineHeight: 24,
  },
  subtitle: {
    ...appTypography.labelLg,
    color: appColors.secondary,
    lineHeight: 18,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: appSpacing.sm,
    flexShrink: 0,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonPressed: {
    backgroundColor: appColors.surfaceContainerHigh,
  },
  notificationDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: appColors.tertiaryContainer,
    borderWidth: 2,
    borderColor: appColors.surface,
  },
  notificationBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 3,
    borderRadius: 8,
    backgroundColor: appColors.tertiaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: appColors.surface,
  },
  notificationBadgeText: {
    color: appColors.onTertiary,
    fontSize: 9,
    lineHeight: 11,
    fontFamily: 'PublicSans_700Bold',
  },
  avatarWrap: {
    width: 32,
    height: 32,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPhoto: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'rgba(0, 70, 74, 0.2)',
    overflow: 'hidden',
  },
  onlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: appColors.primary,
    borderWidth: 2,
    borderColor: appColors.surface,
  },
});
