import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing } from '../theme';

export const loginHeroHeaderStyles = StyleSheet.create({
  header: {
    backgroundColor: appColors.primary,
    paddingHorizontal: 24,
    paddingBottom: 40,
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    top: -64,
    right: -64,
    width: 224,
    height: 224,
    borderRadius: 112,
    backgroundColor: 'rgba(30, 94, 99, 0.4)',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 24,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoWrap: {
    width: 40,
    height: 40,
    borderRadius: appRadii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 28,
    height: 28,
  },
  brandName: {
    fontSize: 20,
    lineHeight: 22,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onPrimary,
  },
  brandSubtitle: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_500Medium',
    color: appColors.primaryFixed,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 2,
  },
  langButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: appRadii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  langButtonPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  langLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onPrimary,
  },
  heroCenter: {
    alignItems: 'center',
    paddingTop: 4,
  },
  authorizedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: appRadii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: 12,
  },
  authorizedText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_500Medium',
    color: appColors.primaryFixed,
  },
  welcomeTitle: {
    fontSize: 24,
    lineHeight: 30,
    fontFamily: 'PublicSans_800ExtraBold',
    color: appColors.onPrimary,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'PublicSans_400Regular',
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    marginTop: 4,
  },
});
