import { StyleSheet } from 'react-native';

import { appColors, appRadii, fontScale, isCompact, ms } from '../theme';

export const loginHeroHeaderStyles = StyleSheet.create({
  header: {
    backgroundColor: appColors.primary,
    paddingHorizontal: ms(20),
    paddingBottom: isCompact ? ms(28) : ms(40),
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    top: -64,
    right: -64,
    width: ms(200),
    height: ms(200),
    borderRadius: ms(100),
    backgroundColor: 'rgba(30, 94, 99, 0.4)',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: isCompact ? ms(16) : ms(24),
    gap: ms(8),
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  logoWrap: {
    width: 40,
    height: 40,
    borderRadius: appRadii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 28,
    height: 28,
  },
  brandName: {
    fontSize: fontScale(18),
    lineHeight: fontScale(22),
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onPrimary,
  },
  brandSubtitle: {
    fontSize: fontScale(10),
    lineHeight: fontScale(13),
    fontFamily: 'PublicSans_500Medium',
    color: appColors.primaryFixed,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 2,
  },
  langButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: appRadii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    flexShrink: 0,
  },
  langButtonPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  langLabel: {
    fontSize: fontScale(11),
    lineHeight: fontScale(15),
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onPrimary,
  },
  heroCenter: {
    alignItems: 'center',
    paddingTop: 4,
    paddingHorizontal: ms(8),
  },
  authorizedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: appRadii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: ms(10),
  },
  authorizedText: {
    fontSize: fontScale(11),
    lineHeight: fontScale(15),
    fontFamily: 'PublicSans_500Medium',
    color: appColors.primaryFixed,
  },
  welcomeTitle: {
    fontSize: fontScale(isCompact ? 22 : 24),
    lineHeight: fontScale(isCompact ? 28 : 30),
    fontFamily: 'PublicSans_800ExtraBold',
    color: appColors.onPrimary,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: fontScale(13),
    lineHeight: fontScale(19),
    fontFamily: 'PublicSans_400Regular',
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    marginTop: 4,
  },
});
