import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const loginAuthCardStyles = StyleSheet.create({
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: 16,
    padding: appSpacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(191, 200, 201, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 30,
    elevation: 4,
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.xl,
    padding: 6,
    gap: 4,
    marginBottom: appSpacing.md,
    borderWidth: 1,
    borderColor: 'rgba(191, 200, 201, 0.2)',
  },
  modeButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: appRadii.lg,
  },
  modeButtonActive: {
    backgroundColor: appColors.primaryContainer,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  modeLabel: {
    fontSize: 13,
    lineHeight: 17,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.secondary,
    flexShrink: 1,
  },
  modeLabelActive: {
    color: appColors.onPrimary,
  },
  fieldGroup: {
    gap: 6,
    marginBottom: 20,
  },
  fieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  fieldHint: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_500Medium',
    color: appColors.secondary,
  },
  inputRow: {
    height: 56,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surface,
    borderWidth: 1,
    borderColor: 'rgba(191, 200, 201, 0.5)',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputRowFocused: {
    borderColor: appColors.primary,
  },
  phonePrefix: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 12,
    marginRight: 8,
    borderRightWidth: 1,
    borderRightColor: 'rgba(191, 200, 201, 0.4)',
  },
  flag: {
    fontSize: 18,
  },
  countryCode: {
    fontSize: 16,
    lineHeight: 20,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onSurface,
    paddingVertical: 0,
  },
  clearButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpSection: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(191, 200, 201, 0.4)',
    gap: 16,
  },
  otpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  otpLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  otpLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  autoDetectBadge: {
    backgroundColor: 'rgba(0, 70, 74, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.full,
  },
  autoDetectText: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.primary,
  },
  otpRow: {
    flexDirection: 'row',
    gap: 6,
  },
  otpBox: {
    flex: 1,
    minWidth: 0,
    height: 48,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surface,
    borderWidth: 1,
    borderColor: 'rgba(191, 200, 201, 0.5)',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
    paddingVertical: 0,
  },
  otpBoxFocused: {
    borderWidth: 2,
    borderColor: appColors.primary,
    backgroundColor: appColors.surfaceContainerHigh,
  },
  otpFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  resendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  resendText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_400Regular',
    color: appColors.secondary,
  },
  resendCountdown: {
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  callOtpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  callOtpLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.primary,
  },
  verifyButton: {
    marginTop: 24,
    height: 56,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: appColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  verifyButtonPressed: {
    backgroundColor: appColors.primaryContainer,
    opacity: 0.96,
  },
  verifyLabel: {
    ...appTypography.labelXl,
    fontSize: 16,
    color: appColors.onPrimary,
  },
  forgotWrap: {
    alignItems: 'center',
    marginTop: 16,
  },
  forgotButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  forgotLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.tertiary,
  },
});
