import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const relieveShiftHandoverCardStyles = StyleSheet.create({
  section: {
    gap: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: appSpacing.sm,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  stepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBadgeText: {
    ...appTypography.labelLg,
    color: appColors.onPrimary,
    fontFamily: 'PublicSans_700Bold',
  },
  stepTitle: {
    ...appTypography.titleLg,
    color: appColors.onSurface,
    flexShrink: 1,
  },
  changeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  changeLabel: {
    ...appTypography.labelLg,
    color: appColors.primary,
  },
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: appRadii.xl,
    padding: appSpacing.md,
    paddingLeft: appSpacing.md + 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  statusSpine: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 8,
    backgroundColor: appColors.primary,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: appRadii.full,
    backgroundColor: appColors.surfaceContainer,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: appColors.primary,
  },
  statusBadgeText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.primary,
  },
  whenLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_600SemiBold',
    color: appColors.onSurfaceVariant,
  },
  date: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
    marginBottom: 4,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  timeText: {
    ...appTypography.bodyXl,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSurface,
  },
  durationBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.sm,
    backgroundColor: appColors.secondaryContainer,
  },
  durationText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.onSecondaryContainer,
  },
  siteBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.lg,
    padding: appSpacing.sm,
  },
  siteCopy: {
    flex: 1,
    minWidth: 0,
  },
  siteName: {
    ...appTypography.labelXl,
    color: appColors.onSurface,
  },
  postLabel: {
    ...appTypography.bodyLg,
    color: appColors.onSurfaceVariant,
    fontFamily: 'PublicSans_500Medium',
  },
  footerRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  eligibleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  eligibleText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_700Bold',
    color: appColors.primary,
    flexShrink: 1,
  },
  supervisorText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'PublicSans_500Medium',
    color: appColors.onSecondaryContainer,
  },
});
