import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const scheduleUpcomingShiftCardStyles = StyleSheet.create({
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: appRadii.xl,
    padding: appSpacing.md,
    gap: appSpacing.xs,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  restCard: {
    backgroundColor: appColors.surfaceContainerLow,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: appSpacing.xs,
    flexWrap: 'wrap',
  },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '50%',
    minWidth: 0,
    flexWrap: 'wrap',
  },
  tomorrowBadge: {
    backgroundColor: appColors.primaryFixed,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: appRadii.full,
    flexShrink: 0,
  },
  tomorrowText: {
    ...appTypography.labelLg,
    color: appColors.onPrimaryFixed,
    fontFamily: 'PublicSans_700Bold',
  },
  dayLabel: {
    ...appTypography.titleLg,
    color: appColors.onSurface,
    flexShrink: 1,
    flex: 1,
    minWidth: 0,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: appColors.surfaceContainerLow,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: appRadii.md,
    flexShrink: 0,
  },
  statusBadgeNight: {
    backgroundColor: appColors.surfaceContainerHigh,
  },
  statusBadgeRest: {
    backgroundColor: appColors.surfaceContainerHighest,
    borderRadius: appRadii.full,
    paddingHorizontal: 10,
  },
  statusText: {
    ...appTypography.labelLg,
    color: appColors.primary,
    fontFamily: 'PublicSans_700Bold',
  },
  statusTextNight: {
    color: appColors.onSurface,
  },
  siteBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: 4,
    gap: appSpacing.sm,
  },
  siteCol: {
    flex: 1,
    minWidth: 0,
  },
  siteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  siteName: {
    ...appTypography.bodyXl,
    color: appColors.onSurface,
    fontFamily: 'PublicSans_600SemiBold',
    flexShrink: 1,
    flex: 1,
    minWidth: 0,
  },
  postName: {
    ...appTypography.bodyLg,
    color: appColors.onSurfaceVariant,
    marginLeft: 24,
  },
  allowanceChip: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(30, 94, 99, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: appRadii.lg,
    maxWidth: '100%',
  },
  allowanceText: {
    ...appTypography.labelLg,
    color: appColors.primaryContainer,
    fontFamily: 'PublicSans_700Bold',
    flexShrink: 1,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 8,
    gap: appSpacing.xs,
    flexWrap: 'wrap',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  timeText: {
    ...appTypography.labelLg,
    color: appColors.secondary,
    flexShrink: 1,
    flex: 1,
    minWidth: 0,
  },
  restBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: appSpacing.sm,
    marginVertical: 4,
  },
  restIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },

  restTitle: {
    ...appTypography.bodyXl,
    color: appColors.onSurface,
    fontFamily: 'PublicSans_700Bold',
  },
  restMessage: {
    ...appTypography.bodyLg,
    color: appColors.onSurfaceVariant,
  },
});
