import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing, appTypography } from '../theme';

export const scheduleTodayShiftHeroStyles = StyleSheet.create({
  card: {
    backgroundColor: appColors.surfaceContainerLowest,
    borderRadius: appRadii.xl,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  spine: {
    width: '100%',
    height: 6,
    backgroundColor: appColors.primary,
  },
  body: {
    padding: appSpacing.md,
    gap: appSpacing.sm,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  todayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: appColors.primaryContainer,
    paddingHorizontal: appSpacing.sm,
    paddingVertical: 4,
    borderRadius: appRadii.full,
  },
  todayBadgeText: {
    ...appTypography.labelLg,
    color: appColors.onPrimary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: appColors.surfaceContainer,
    paddingHorizontal: appSpacing.sm,
    paddingVertical: 4,
    borderRadius: appRadii.full,
  },
  liveDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: appColors.primary,
  },
  liveText: {
    ...appTypography.labelLg,
    color: appColors.primary,
    fontFamily: 'PublicSans_700Bold',
  },
  siteName: {
    ...appTypography.headlineSm,
    color: appColors.onSurface,
    marginTop: 4,
  },
  postRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  postText: {
    ...appTypography.bodyLg,
    color: appColors.onSurfaceVariant,
    fontFamily: 'PublicSans_500Medium',
    flex: 1,
  },
  timeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: appColors.surfaceContainerLow,
    borderRadius: appRadii.lg,
    padding: appSpacing.sm,
  },
  timeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  timeRange: {
    ...appTypography.labelXl,
    color: appColors.onSurface,
    lineHeight: 22,
  },
  timeMeta: {
    ...appTypography.labelLg,
    color: appColors.secondary,
  },
  sunCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: appColors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supervisorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: appSpacing.xs,
    paddingVertical: 4,
  },
  supervisorLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  supervisorIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: appColors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supervisorName: {
    ...appTypography.labelLg,
    color: appColors.onSurface,
    fontFamily: 'PublicSans_600SemiBold',
  },
  supervisorRole: {
    ...appTypography.labelLg,
    color: appColors.secondary,
    lineHeight: 16,
  },
  callButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: appColors.surfaceContainerHigh,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: appRadii.lg,
  },
  callText: {
    ...appTypography.labelLg,
    color: appColors.primary,
    fontFamily: 'PublicSans_700Bold',
  },
  actions: {
    flexDirection: 'row',
    gap: appSpacing.sm,
    paddingTop: 8,
  },
  actionOutline: {
    flex: 1,
    minHeight: 52,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.surfaceContainer,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionPrimary: {
    flex: 1,
    minHeight: 52,
    borderRadius: appRadii.xl,
    backgroundColor: appColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  actionOutlineText: {
    ...appTypography.labelXl,
    color: appColors.primary,
  },
  actionPrimaryText: {
    ...appTypography.labelXl,
    color: appColors.onPrimary,
  },
});
